services:
  mysql:
    image: mysql
    container_name: db_student_management_system
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_management
      
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cgvs_network

networks:
  cgvs_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
