name: Release Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
          fetch-tags: true  # We need tags for release versioning
          show-progress: false  # Reduce log noise
      
      - name: Set up JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'    # Enable Gradle caching
          check-latest: true # Ensure we have the latest patch version
          java-package: 'jdk'
      
      - name: Setup Gradle
        uses: gradle/actions@v4.4.0
        
      - name: Build Windows MSI
        run: ./gradlew packageReleaseMsi
        
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-msi
          path: composeApp/build/compose/binaries/main-release/msi/*.msi
          if-no-files-found: error  # Fail if no MSI is generated
          retention-days: 5         # Keep for 5 days
          compression-level: 0      # No compression for binary files
          overwrite: true          # Replace if exists

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
          fetch-tags: true  # We need tags for release versioning
          show-progress: false  # Reduce log noise
      
      - name: Set up JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'    # Enable Gradle caching
          check-latest: true # Ensure we have the latest patch version
          java-package: 'jdk'
          
      - name: Setup Gradle
        uses: gradle/actions@v4.4.0
        
      - name: Build Linux DEB
        run: ./gradlew packageReleaseDeb
        
      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-deb
          path: composeApp/build/compose/binaries/main-release/deb/*.deb
          if-no-files-found: error  # Fail if no DEB is generated
          retention-days: 5         # Keep for 5 days
          compression-level: 0      # No compression for binary files
          overwrite: true          # Replace if exists

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-msi/**/*.msi
            linux-deb/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}